volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: olmazurova/foodgram_backend
    env_file:
      - .env
    volumes:
      - static:/backend_static
      - media:/var/www/foodgram/media/
    depends_on:
      - db

  frontend:
    env_file:
      - .env
    image: olmazurova/foodgram_frontend
    command:
      - cp -r /app/build/. /static_frontend/
    volumes:
      - static:/static_frontend

  gateway:
    image: olmazurova/foodgram_gateway
    env_file:
      - .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend