# Generated by Django 3.2.3 on 2025-07-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение блюда', upload_to='media/recipes/', verbose_name='изображение'),
        ),
    ]
