# Generated by Django 3.2.3 on 2025-07-20 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20250716_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='in_shopping_cart',
            new_name='is_in_shopping_cart',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Укажите время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='время приготовления'),
        ),
    ]
