# Generated by Django 3.2.3 on 2025-07-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20250720_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='favorited',
            new_name='is_favorited',
        ),
    ]
